# Generated by Django 5.2.14 on 2026-05-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_phone', models.CharField(max_length=15)),
                ('crop', models.CharField(max_length=100)),
                ('soil', models.CharField(max_length=100)),
                ('season', models.CharField(max_length=100)),
                ('prediction', models.CharField(max_length=100)),
                ('irrigation', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
